# -*- coding: utf-8 -*-
"""sprint4_final_project_starter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lLTiXQ7wRRjG-xhfN2f671DkepcHx1d2

# Sprint 4 Project: E-Commerce Customer Behavior EDA

Welcome to your Sprint 4 final project. In this project, you will apply everything you've learned across Sprints 1–4 to perform a complete Exploratory Data Analysis on the **Olist Brazilian E-Commerce dataset** — real data from a real e-commerce platform.


## Dataset

You'll work with 7 CSV files from the Olist e-commerce dataset:

| File | Rows | Description |
|---|---|---|
| `olist_orders_dataset.csv` | 99,441 | Orders with timestamps and status |
| `olist_order_items_dataset.csv` | 112,650 | Items per order with price and freight |
| `olist_customers_dataset.csv` | 99,441 | Customer ID, city, state |
| `olist_products_dataset.csv` | 32,951 | Products with category and dimensions |
| `olist_order_reviews_dataset.csv` | 99,224 | Review scores (1–5 stars) |
| `olist_order_payments_dataset.csv` | 103,886 | Payment type and value |
| `product_category_name_translation.csv` | 71 | Portuguese → English category names |

Let's get started!

---

## Setup

Run the cells below to import the libraries you'll need and load the datasets. The data is hosted on GitHub, so you can load it with one line of code per file — no uploads required.
"""

# Import libraries
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

# Confirm versions
print(f"pandas version: {pd.__version__}")
print("Setup complete!")

# Load the 7 datasets from the curriculum GitHub repo
BASE_URL = 'https://practicum-content.s3.us-west-1.amazonaws.com/data-analytics/eda-project/'

orders = pd.read_csv(BASE_URL + 'olist_orders_dataset.csv')
items = pd.read_csv(BASE_URL + 'olist_order_items_dataset.csv')
customers = pd.read_csv(BASE_URL + 'olist_customers_dataset.csv')
products = pd.read_csv(BASE_URL + 'olist_products_dataset.csv')
reviews = pd.read_csv(BASE_URL + 'olist_order_reviews_dataset.csv')
payments = pd.read_csv(BASE_URL + 'olist_order_payments_dataset.csv')
translation = pd.read_csv(BASE_URL + 'product_category_name_translation.csv')

print(f"orders:      {orders.shape}")
print(f"items:       {items.shape}")
print(f"customers:   {customers.shape}")
print(f"products:    {products.shape}")
print(f"reviews:     {reviews.shape}")
print(f"payments:    {payments.shape}")
print(f"translation: {translation.shape}")

# Set up an in-memory SQLite database with all 7 tables
# This lets you run SQL queries directly against the DataFrames
conn = sqlite3.connect(':memory:')

orders.to_sql('orders', conn, index=False, if_exists='replace')
items.to_sql('items', conn, index=False, if_exists='replace')
customers.to_sql('customers', conn, index=False, if_exists='replace')
products.to_sql('products', conn, index=False, if_exists='replace')
reviews.to_sql('reviews', conn, index=False, if_exists='replace')
payments.to_sql('payments', conn, index=False, if_exists='replace')
translation.to_sql('translation', conn, index=False, if_exists='replace')

print("SQLite database ready. You can now run SQL queries with pd.read_sql().")

"""---

## Question 1: Inspect the orders DataFrame

**Your task:** For the `orders` DataFrame:
1. Print its shape
2. Print the first 5 rows with `.head()`
3. Print column info with `.info()`

This is the very first thing every analyst does with a new dataset.

*Skills: Sprint 4 Ch 01 (Pandas inspection)*
"""

print(f"orders:      {orders.shape}")
print(f"items:       {items.shape}")
print(f"customers:   {customers.shape}")
print(f"products:    {products.shape}")
print(f"reviews:     {reviews.shape}")
print(f"payments:    {payments.shape}")
print(f"translation: {translation.shape}")

print(orders.head())
print('\n')
print(orders.info())

print(items.head())
print('\n')
print(items.info())

print(customers.head())
print('\n')
print(customers.info())

print(products.head())
print('\n')
print(products.info())

print(reviews.head())
print('\n')
print(reviews.info())

print(payments.head())
print('\n')
print(payments.info())

print(translation.head())
print(print('\n'))
print(translation.info())

"""---

## Question 2: Clean the orders data

The `orders` DataFrame has timestamp columns stored as strings, and a few have missing values.

**Your task:**
1. Use `.isnull().sum()` to count missing values in each column of `orders`
2. Convert `order_purchase_timestamp` and `order_delivered_customer_date` to datetime using `pd.to_datetime()`
3. Print the dtypes after conversion to verify

*Skills: Sprint 4 Ch 02 (Cleaning, dtype conversion)*
"""

#Calculate the null value for each columns in Orders table:
count_null = orders.isnull().sum()
print(count_null)

#Convert data type:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])

#Check data type:
orders.dtypes

"""---

## Question 3: Order status breakdown (SQL)

**Your task:** Write a SQL query against the `orders` table that returns:
- `order_status`
- `num_orders` — count of orders with that status
- `pct` — percentage of total orders, rounded to 2 decimals

Sort by `num_orders` descending. Save the result to a DataFrame called `status_summary` and print it.

**Hint:** Use `pd.read_sql("...", conn)`. The percentage trick is `COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders)`.

*Skills: Sprint 2 (SQL aggregation), Sprint 4 Ch 03 (Descriptive stats)*
"""

query = 'SELECT order_status, COUNT(order_status) AS num_orders, ROUND(COUNT(*)*100/(SELECT COUNT(*) FROM orders),2) AS pct FROM orders GROUP BY order_status '

status_summary = pd.read_sql(query, conn)
print(status_summary)

status_summary.plot(kind='bar', x = 'order_status', rot = 50)

"""---

## Question 4: Top 10 highest-revenue orders (SQL JOIN)

Each order can have multiple items. Total order revenue = sum of `price + freight_value` across all its items.

**Your task:** Write a SQL query that JOINs `orders` and `items` to find the **10 highest-revenue orders**. Return:
- `order_id`
- `order_status`
- `total_revenue` — rounded to 2 decimals

Save the result to `top_orders` and print it.

*Skills: Sprint 2 (SQL JOIN, GROUP BY), Sprint 4 Ch 06 (combining tables)*
"""

query= '''SELECT i.order_id, o.order_status, ROUND(SUM(i.price),2) as total_revenue
           FROM items i
           LEFT JOIN orders o ON i.order_id = o.order_id
           WHERE o.order_status = 'delivered'
           GROUP BY i.order_id
           ORDER BY total_revenue DESC
           LIMIT 10 '''
top_orders = pd.read_sql(query, conn)
print(top_orders)

"""---

## Question 5: English product categories (pandas merge)

The `products` table has a Portuguese category column called `product_category_name`. The `translation` table maps each Portuguese name to its English equivalent.

**Your task:**
1. Use `products.merge(translation, on='product_category_name', how='left')` to add the English column. Save it to `products_eng`.
2. Find the **top 10 categories by number of products** using `value_counts()` on the `product_category_name_english` column. Save to `top_categories` and print it.

*Skills: Sprint 4 Ch 06 (pandas merge), Ch 03 (value_counts)*
"""

products_eng = products.merge(translation, on='product_category_name', how='left')

top_categories = products_eng['product_category_name_english'].value_counts()

print(f"Top 10 categories by number of products is: \n\n", top_categories.head(10))

"""---

## Question 6: Revenue and average review score by category

Now you'll combine three tables and compute multiple metrics per category.

**Your task:**
1. Build a DataFrame that merges `items` with `products_eng` (to get categories), then merges with `reviews` (to get scores). The shared key chain is: `items.product_id → products_eng.product_id` and `items.order_id → reviews.order_id`.
2. Add a `revenue` column = `price + freight_value`
3. Group by `product_category_name_english` and aggregate:
   - `total_revenue` = sum of `revenue`
   - `avg_review` = mean of `review_score`
   - `n_items` = count of `order_id`
4. Sort by `total_revenue` descending and show the **top 10 categories**. Save to `category_summary`.

*Skills: Sprint 4 Ch 06 (multi-table merge, groupby with multiple aggregations)*
"""

# Build a DataFrame that merges items with products_eng (to get categories), then merges with reviews (to get scores).
categories = items.merge(products_eng, on = 'product_id', how = 'left')
scores = categories.merge(reviews, on = 'order_id', how = 'left')

#Add a revenue column = price + freight_value
scores['revenue'] = scores['price'] + scores['freight_value']

#Group by product_category_name_english and aggregate:
category_summary = scores.groupby('product_category_name_english').agg(
    total_revenue = ('revenue', 'sum'),
    avg_review = ('review_score', 'mean'),
    n_items = ('order_id','count')
)
categories_summary = category_summary.sort_values(by='total_revenue', ascending = False)
categories_summary.columns = ['Total Revenue', 'Avg Review Score', 'Total Orders']


print(categories_summary.head(10))

#Group by product_category_name_english and concat to make the categories summary table:

total_revenue = scores.groupby('product_category_name_english')['revenue'].sum()
avg_review = scores.groupby('product_category_name_english')['review_score'].mean()
n_items = scores.groupby('product_category_name_english')['order_id'].count()

concat = pd.concat([total_revenue, avg_review, n_items], axis = 'columns')

categories_summary1 = concat.sort_values(by='revenue', ascending = False)
categories_summary1.columns = ['Total Revenue', 'Avg Review Score', 'Total Orders']

print(categories_summary1.head(10))

"""---

## Question 7: Top 10 customer states (SQL + bar chart)

**Your task:**
1. Write a SQL query that returns the **top 10 customer states** by number of customers. Columns: `customer_state`, `num_customers`. Save to `state_top10`.
2. Create a **bar chart** of `num_customers` by `customer_state`. Add a title and rotate the x-tick labels if they overlap.

*Skills: Sprint 2 (SQL GROUP BY), Sprint 4 Ch 04 (bar chart)*
"""

query = '''
SELECT
  customer_state,
  COUNT(customer_id) as num_customers
FROM customers
GROUP BY customer_state
ORDER BY num_customers DESC
LIMIT 10
'''
state_top10 = pd.read_sql(query, conn)
total_customers = state_top10['num_customers'].sum()
state_top10['pct'] = state_top10['num_customers']/total_customers*100

print(state_top10)

state_top10.plot(kind='bar', x = 'customer_state', y = 'num_customers',
                 title = ' Top 10 Customer by States',
                 rot = 360)
plt.show()

"""---

## Question 8: Monthly order trend (line chart)

**Your task:**
1. From the cleaned `orders` DataFrame (with datetime columns from Q2), extract a `year_month` period from `order_purchase_timestamp` using `.dt.to_period('M')`
2. Count orders per month — save to a DataFrame called `monthly_orders` with columns `year_month` and `num_orders`
3. Plot a **line chart** of `num_orders` over time. Add a title.

**Hint:** `orders['order_purchase_timestamp'].dt.to_period('M').value_counts().sort_index()` is a fast way to get monthly counts. Convert the period index back to string for plotting.

*Skills: Sprint 4 Ch 02 (datetime), Ch 03 (groupby), Ch 04 (line chart)*
"""

#From the cleaned orders DataFrame (with datetime columns from Q2), extract a year_month period from order_purchase_timestamp using .dt.to_period('M')

orders['year_month'] = orders['order_purchase_timestamp'].dt.to_period('M')

monthly_orders = orders.groupby('year_month')['order_id'].count()
monthly_orders.plot(kind='line', x = 'year_month', title = 'Number of Order by Months',
                    ylabel = 'Number of orders')

plt.show()

orders['order_purchase_timestamp'].dt.to_period('M').value_counts().sort_index()

year_order = orders['order_purchase_timestamp'].dt.to_period('Y').value_counts().sort_index()

business_health = (year_order['2018'] - year_order['2017'])/year_order['2017']*100

print(f"Increasing {business_health:.2f}% number of orders from 2017 to 2018")

"""---

## Question 9: Does delivery speed affect review scores?

This is a real business question: do customers who get their orders faster leave better reviews?

**Your task:**
1. From `orders`, keep only rows where `order_delivered_customer_date` is not null
2. Add a `delivery_days` column = (delivery date − purchase date) in days. **Hint:** subtract the two datetime columns and use `.dt.days`
3. Merge with `reviews` on `order_id` to get the `review_score` for each order
4. Compute the **correlation** between `delivery_days` and `review_score` using `.corr()`
5. Group by `review_score` and show the **average delivery days** for each score (1 through 5)
6. Plot a bar chart of average delivery days by review score

What pattern do you see? Add a markdown cell with your interpretation.

*Skills: Sprint 4 Ch 03 (correlation), Ch 04 (visualization), Ch 06 (merge + groupby)*
"""

#From orders, keep only rows where order_delivered_customer_date is not null

orders_clean = orders.dropna(subset = 'order_delivered_customer_date')

#Add a delivery_days column = (delivery date − purchase date) in days. Hint: subtract the two datetime columns and use .dt.days
orders_clean['delivery_days'] = (orders_clean['order_delivered_customer_date']  - orders_clean['order_purchase_timestamp']).dt.days

#Merge with reviews on order_id to get the review_score for each order

merge = orders_clean.merge(reviews, on = 'order_id', how = 'left')

corr = merge['delivery_days'].corr(merge['review_score'])

print('The correlation between delivery_days and review_score is: ', corr)

avg_deliverydays_by_score = merge.groupby('review_score')['delivery_days'].mean()

avg_deliverydays_by_score.plot(kind='bar', title = 'Average delivery days by Review Score'
                                , rot = 360, xlabel = 'Review Score', ylabel = 'Avg Delivery Days')

plt.show()

#Delivery speech strongly affects customer satisfaction.
#Recommendation: Monitor the delivery processes, analyze the delivery days by regions, improving delivery service.

"""**Your interpretation:**

*Replace this text with 2–3 sentences explaining what the correlation and bar chart tell you about the relationship between delivery speed and review scores.*

---

## Question 10: Final Report

Write a **2–3 paragraph executive summary** of your findings as a markdown cell below. A good report answers:

- **What is the overall health of the business?** (Use Q3, Q8 — order volumes and trends)
- **Which product categories should we double down on?** (Use Q6 — revenue + review scores together)
- **Where are our customers and how do we serve them?** (Use Q7, Q9 — geography and delivery speed)
- **What is one specific recommendation you would make to the leadership team?**

Write as if you're presenting to a non-technical executive. Use plain language. Reference specific numbers from your analysis.

*Skills: Sprint 4 Ch 06 (analytical reporting)*

# **Executive Summary**


**Business Health**
The overall health of the business is strong, driven by a highly successful logistics pipeline where the vast majority of customer orders are successfully delivered. The platform is experiencing steady growth, with the total number of orders increasing by 21.54% from 2017 to 2018.

**Top Categories**
To maximize growth, leadership should double down on seven core high-performing categories: health_beauty, watches_gifts, bed_bath_table, sports_leisure, computers_accessories, furniture_decor, and housewares. These categories represent the pillars of our revenue, each generating over $1M in total sales while maintaining high volume and exceptional customer satisfaction, averaging a 4.0 review score.

**Customer Geography & Delivery**
Our customer base is highly concentrated geographically. The top three states account for nearly three-quarters of all business: São Paulo (SP) leads with 46% of all customers, followed by Rio de Janeiro (RJ) at 14%, and Minas Gerais (MG) at 13%. Because customer satisfaction is strongly correlated with delivery operations, maintaining service standards in these high-volume hubs is critical.

**Strategic Recommendations**
Regional Demand Analysis: Conduct localized market research to better understand specific product preferences and buying behaviors within our top-performing states.

**Proactive Logistics Monitoring:** Implement a targeted monitoring system for delayed or at-risk shipments to actively reduce low review scores caused by delivery bottlenecks.

**Geographic Expansion Strategy:** Investigate the root causes of lower order volumes in minor states. Analyze whether the barriers are tied to local marketing gaps, non-competitive pricing, prolonged delivery windows, or lacking regional demand to capture untapped market share.

## Executive Summary

*Replace this section with your findings.*

### Business Health


### Top Categories


### Customer Geography & Delivery


### Recommendation
"""